# Generated by Django 5.2.17 on 2026-09-30 10:24

import trips.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.CharField(default=trips.models.new_trip_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('current_label', models.CharField(max_length=200)),
                ('pickup_label', models.CharField(max_length=200)),
                ('dropoff_label', models.CharField(max_length=200)),
                ('cycle_used_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_miles', models.DecimalField(decimal_places=1, max_digits=8)),
                ('days', models.PositiveSmallIntegerField()),
                ('engine_version', models.CharField(max_length=20)),
                ('request', models.JSONField()),
                ('result', models.JSONField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
