/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/geocode/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search US places (autocomplete)
         * @description Up to limit US places matching q; towns first, street addresses when q has digits.
         */
        get: operations["geocode_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/geocode/reverse/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Nearest US town to a coordinate
         * @description The nearest US town to lat/lng, or 404 when there is none.
         */
        get: operations["geocode_reverse_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan a trip
         * @description Geocodes the stops, routes a truck, applies the HOS rules, and saves the plan.
         */
        post: operations["trips_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a planned trip */
        get: operations["trips_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Assumptions: {
            rules: components["schemas"]["RuleDescription"][];
            notes: string[];
        };
        Bracket: {
            start_minute: number;
            end_minute: number;
            place: string;
        };
        DailyLog: {
            date: string;
            day_number: number;
            from: string;
            to: string;
            /** Format: double */
            miles_today: number;
            segments: components["schemas"]["Segment"][];
            totals: components["schemas"]["Totals"];
            remarks: components["schemas"]["Remark"][];
            brackets: components["schemas"]["Bracket"][];
            header: components["schemas"]["LogHeader"];
            recap: components["schemas"]["Recap"];
        };
        /** @description OpenAPI description of the error envelope. */
        Error: {
            error: components["schemas"]["ErrorBody"];
        };
        ErrorBody: {
            code: string;
            message: string;
            field?: string;
            details?: unknown;
        };
        Geometry: {
            type: string;
            coordinates: number[][];
        };
        HomeTimeZone: {
            iana: string;
            abbreviation: string;
            utc_offset: string;
        };
        /**
         * @description * `start` - start
         *     * `pickup` - pickup
         *     * `dropoff` - dropoff
         *     * `fuel` - fuel
         *     * `break` - break
         *     * `rest` - rest
         *     * `restart` - restart
         * @enum {string}
         */
        KindEnum: "start" | "pickup" | "dropoff" | "fuel" | "break" | "rest" | "restart";
        LocationInputRequest: {
            label: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lng?: number;
        };
        LogDetails: {
            driver_name?: string;
            co_driver_name?: string;
            carrier_name?: string;
            main_office_address?: string;
            home_terminal_address?: string;
            truck_number?: string;
            trailer_number?: string;
            shipping_document?: string;
            shipper_commodity?: string;
        };
        LogDetailsRequest: {
            driver_name?: string;
            co_driver_name?: string;
            carrier_name?: string;
            main_office_address?: string;
            home_terminal_address?: string;
            truck_number?: string;
            trailer_number?: string;
            shipping_document?: string;
            shipper_commodity?: string;
        };
        LogHeader: {
            driver_name?: string;
            co_driver_name?: string;
            carrier_name?: string;
            main_office_address?: string;
            home_terminal_address?: string;
            truck_number?: string;
            trailer_number?: string;
            shipping_document?: string;
            shipper_commodity?: string;
            time_zone: string;
        };
        /** @description A US place: a display label and its coordinates. */
        Place: {
            label: string;
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
        };
        PlanTripRequest: {
            current_location: components["schemas"]["LocationInputRequest"];
            pickup_location: components["schemas"]["LocationInputRequest"];
            dropoff_location: components["schemas"]["LocationInputRequest"];
            /** Format: double */
            current_cycle_used_hours: number;
            /** @description Local home-terminal time, YYYY-MM-DDTHH:MM. Defaults to now. */
            start_time?: string;
            log_details?: components["schemas"]["LogDetailsRequest"];
        };
        Recap: {
            /** Format: double */
            on_duty_today: number;
            /** Format: double */
            a_last_7_days: number;
            /** Format: double */
            b_available_tomorrow: number;
            /** Format: double */
            c_last_5_days: number;
        };
        Remark: {
            minute: number;
            time: string;
            place: string;
            note: string;
        };
        Route: {
            geometry: components["schemas"]["Geometry"];
            legs: components["schemas"]["RouteLeg"][];
        };
        RouteLeg: {
            from: string;
            to: string;
            /** Format: double */
            miles: number;
            /** Format: double */
            hours: number;
            /** @description Turn-by-turn directions; consecutive steps on the same road are merged. Empty when the leg has no driving or the trip was saved before directions existed. */
            steps: components["schemas"]["RouteStep"][];
        };
        RouteStep: {
            instruction: string;
            /** @description The road this step runs on; "" when it has no name. */
            road: string;
            /** Format: double */
            miles: number;
            minutes: number;
        };
        RuleCheck: {
            id: string;
            title: string;
            citation: string;
            /** Format: double */
            limit: number;
            /** Format: double */
            observed: number;
            unit: string;
            passed: boolean;
        };
        RuleDescription: {
            label: string;
            value: string;
            source: string;
        };
        Segment: {
            status: components["schemas"]["StatusEnum"];
            start_minute: number;
            end_minute: number;
        };
        /**
         * @description * `off_duty` - off_duty
         *     * `sleeper_berth` - sleeper_berth
         *     * `driving` - driving
         *     * `on_duty` - on_duty
         * @enum {string}
         */
        StatusEnum: "off_duty" | "sleeper_berth" | "driving" | "on_duty";
        Stop: {
            id: string;
            kind: components["schemas"]["KindEnum"];
            status: components["schemas"]["StatusEnum"];
            starts_at: string;
            ends_at: string;
            duration_minutes: number;
            /** Format: double */
            mile: number;
            /** Format: double */
            lat: number;
            /** Format: double */
            lng: number;
            place: string;
        };
        StopCounts: {
            fuel: number;
            break: number;
            rest: number;
            restart: number;
        };
        Summary: {
            /** Format: double */
            total_miles: number;
            /** Format: double */
            driving_hours: number;
            /** Format: double */
            on_duty_hours: number;
            starts_at: string;
            arrives_at: string;
            days: number;
            stops: components["schemas"]["StopCounts"];
        };
        Totals: {
            /** Format: double */
            off_duty: number;
            /** Format: double */
            sleeper_berth: number;
            /** Format: double */
            driving: number;
            /** Format: double */
            on_duty: number;
        };
        TripInputs: {
            current_location: components["schemas"]["Place"];
            pickup_location: components["schemas"]["Place"];
            dropoff_location: components["schemas"]["Place"];
            /** Format: double */
            current_cycle_used_hours: number;
            start_time: string;
            log_details: components["schemas"]["LogDetails"];
        };
        TripResponse: {
            id: string;
            created_at: string;
            engine_version: string;
            inputs: components["schemas"]["TripInputs"];
            home_time_zone: components["schemas"]["HomeTimeZone"];
            summary: components["schemas"]["Summary"];
            route: components["schemas"]["Route"];
            stops: components["schemas"]["Stop"][];
            daily_logs: components["schemas"]["DailyLog"][];
            compliance: components["schemas"]["RuleCheck"][];
            assumptions: components["schemas"]["Assumptions"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    geocode_list: {
        parameters: {
            query: {
                limit?: number;
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Place"][];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    geocode_reverse_retrieve: {
        parameters: {
            query: {
                lat: number;
                lng: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Place"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    trips_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanTripRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    trips_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
